export const SET_AUTH = "SET_AUTH";

//course reducer
export const COURSE_LOADED_SUCCESS = "COURSE_LOADED_SUCCESS";
export const COURSE_LOADED_FAILED = "COURSE_LOADED_FAILED";
export const SELECT_COURSE_INFO = "SELECT_COURSE_INFO";
export const ADD_COURSE = "ADD_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";

//attendance reducer
export const ATTENDANCE_LOADED_SUCCESS = "ATTENDANCE_LOADED_SUCCESS";
export const ATTENDANCE_LOADED_FAILED = "ATTENDANCE_LOADED_FAILED";
export const DELETE_ATTENDANCE = "DELETE_ATTENDANCE";
export const UPDATE_ATTENDANCE = "UPDATE_ATTENDANCE";
export const CLEAR_ATTENDANCE = "CLEAR_ATTENDANCE";
export const CREATE_ATTENDANCE = "CREATE_ATTENDANCE";

//student reducer
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const SET_FOUND_STUDENTS = "SET_FOUND_STUDENTS";
export const SELECT_STUDENT = "SELECT_STUDENT";
export const REMOVE_STUDENT_FROM_COURSE = "REMOVE_STUDENT_FROM_COURSE";
